const LOAD_ALL_PRODUCT = 'LOAD_PRODUCTS';
const GET_A_PRODUCT = 'GET_A_PRODUCT';
const  ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export default { LOAD_ALL_PRODUCT,GET_A_PRODUCT,ADD_TO_CART, REMOVE_FROM_CART};
