export default {
  PRODUCT_SUCESSFULLY_ADDED: 'PRODUCT_SUCESSFULLY_ADDED',
  ADDING_PRODUCT: 'ADDING_PRODUCT',
  ADD_ERROR: 'ADD_ERROR',
  SIGNING_UP: 'SIGNING_UP',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
};
