const LOAD_ALL_PRODUCT = 'LOAD_PRODUCTS';
const ADD_PRODUCT = 'ADD_PRODUCT';
const SET_ADD_STATE = 'SET_ADD_STATE';
const SET_ADD_ERROR = 'SET_ADD_ERROR';
const PRODUCT_SUCESSFULLY_ADDED = 'PRODUCT_SUCESSFULLY_ADDED';
const ADDING_PRODUCT = 'ADDING_PRODUCT';
const ADD_ERROR = 'ADD_ERROR';

export default { LOAD_ALL_PRODUCT, ADD_PRODUCT,PRODUCT_SUCESSFULLY_ADDED,ADDING_PRODUCT,ADD_ERROR,SET_ADD_STATE,SET_ADD_ERROR};
